sudo: required
dist: bionic
language: node_js
node_js:
  - "8"
before_install:
  - nvm install v8.4.0
  - npm version
install:
  - npm install
script:
  - npm run gulp -- travis
cache: npm
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
