sudo: required
dist: bionic
language: node_js
node_js:
  - '12'
before_install:
  - npm version
install:
  - npm install
script:
  - npm run gulp -- travis
cache:
  directories:
    - node_modules
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
