sudo: required
dist: bionic
language: node_js
node_js:
  - "8"
before_install:
  - npm version
install:
  - npm install
before_script:
  - export NODE_OPTIONS=–max_old_space_size=8192
script:
  - npm run gulp -- travis
cache:
  directories:
    - node_modules
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
